import Link from "next/link"


export const metadata = {
  title: "Curso de NextJs",
  description: 'Generated by Elto',
}

export default function Contacto() {
  return (
    <div>
      <h1>Contacto</h1>
      <br />
      <button ><Link href="/" >Back to Home</Link></button>

    </div>
  )
}




