import Link from "next/link"
import "./global.css"

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

import { Metadata } from "next"

export const metadata: Metadata = {
  title: {
    template: "template",
    default: "default",
    absolute: " absolute",
  }
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <h2>App Header</h2>
          <nav>
            <Link href="/" >Home</Link>
            -
            <Link href="/acerca" >About</Link>
            -
            <Link href="/blog">Blog</Link>
            -
            <Link href="/contacto">Contact</Link>
            -
            <Link href="/productos">products</Link>
            -
            <Link href="/cuenta/login">account</Link>
            -
            <Link href="/cuenta/registro">Register</Link>
            -
            <Link href="/cuenta/password">Recover Password</Link>
            -
            <Link href="/dashboard">Dashboard</Link>
          </nav>
        </header>
        <main>
          {children}
        </main>
        <footer>
          <h6>App footer</h6>
        </footer>
      </body>
    </html>
  )
}
